[package]
name = "geocoderpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "geocoderpy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
country-geocoder = {git = "https://github.com/ringsaturn/country-geocoder"}
lazy_static = "1.4.0"
geo = "0.26.0"

